"""add on delete constraint to a target

Revision ID: 0a0efa1aa41a
Revises: 8b5d0eddd753
Create Date: 2025-05-21 16:13:22.567981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0efa1aa41a'
down_revision: Union[str, None] = '8b5d0eddd753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('targets_mission_id_fkey', 'targets', type_='foreignkey')
    op.create_foreign_key(None, 'targets', 'missions', ['mission_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'targets', type_='foreignkey')
    op.create_foreign_key('targets_mission_id_fkey', 'targets', 'missions', ['mission_id'], ['id'])
    # ### end Alembic commands ###
